import { validateMemoSchema } from "./MemoSchemaValidator";
import { validateConclusionProvenance, ProvenanceLink } from "./ConclusionProvenanceBinder";
import { checkFactConclusionTraceability, TraceabilityLink } from "./FactConclusionTraceabilityChecker";
import { verifyUncertaintyDisclosure, EngineVerdict, MemoDisclosure } from "./UncertaintyDisclosureVerifier";
import { verifyContradictionDisclosure, EngineDispute, MemoContradictionDisclosure } from "./ContradictionDisclosureVerifier";
import { blockUnsupportedConclusions, MemoConclusion } from "./UnsupportedConclusionBlocker";
import type { MemoSectionType } from "./OutputContracts";

/**
 * P8-10 / P10-08: Output Enforcement Gate.
 * 
 * Single source of truth for legal memo validation. Combines schema, 
 * provenance, traceability, and disclosure checks. 
 * Fails closed if any output defect is detected.
 */

export type OutputEvaluationInput = {
  presentSections: readonly MemoSectionType[];
  provenanceLinks: readonly ProvenanceLink[];
  traceabilityLinks: readonly TraceabilityLink[];
  validFactIds: readonly string[];
  engineVerdicts: readonly EngineVerdict[];
  memoUncertaintyDisclosures: readonly MemoDisclosure[];
  engineDisputes: readonly EngineDispute[];
  memoContradictionDisclosures: readonly MemoContradictionDisclosure[];
  memoConclusions: readonly MemoConclusion[];
  supportedConclusionIds: readonly string[];
};

export type OutputDefect = {
  category: "SCHEMA" | "PROVENANCE" | "TRACEABILITY" | "UNCERTAINTY" | "CONTRADICTION" | "UNSUPPORTED_CONCLUSION";
  description: string;
};

export type OutputEvaluationResult = {
  isValid: boolean;
  defects: OutputDefect[];
};

export function enforceOutputRules(input: OutputEvaluationInput): OutputEvaluationResult {
  const defects: OutputDefect[] = [];

  // 1. Schema Check
  const schemaResult = validateMemoSchema(input.presentSections);
  if (!schemaResult.isValid) {
    defects.push({ category: "SCHEMA", description: `Missing required sections: [${schemaResult.missingSections.join(", ")}]` });
  }

  // 2. Provenance Check
  const provenanceResult = validateConclusionProvenance(input.provenanceLinks);
  if (!provenanceResult.isValid) {
    defects.push({ category: "PROVENANCE", description: `Conclusions lack deterministic source mapping: [${provenanceResult.unboundConclusions.join(", ")}]` });
  }

  // 3. Traceability Check
  const traceabilityResult = checkFactConclusionTraceability(input.traceabilityLinks, input.validFactIds);
  if (!traceabilityResult.isValid) {
    defects.push({ category: "TRACEABILITY", description: `Referenced facts not in verified pool: [${traceabilityResult.untraceableFacts.join(", ")}]` });
  }

  // 4. Uncertainty Disclosure Check
  const uncertaintyResult = verifyUncertaintyDisclosure(input.engineVerdicts, input.memoUncertaintyDisclosures);
  if (!uncertaintyResult.isValid) {
    defects.push({ category: "UNCERTAINTY", description: `Undisclosed INDETERMINATE verdicts: [${uncertaintyResult.missingDisclosures.join(", ")}]` });
  }

  // 5. Contradiction Disclosure Check
  const contradictionResult = verifyContradictionDisclosure(input.engineDisputes, input.memoContradictionDisclosures);
  if (!contradictionResult.isValid) {
    defects.push({ category: "CONTRADICTION", description: `Undisclosed factual disputes: [${contradictionResult.missingDisclosures.join(", ")}]` });
  }

  // 6. Unsupported Conclusion Check
  const unsupportedResult = blockUnsupportedConclusions(input.memoConclusions, input.supportedConclusionIds);
  if (!unsupportedResult.isValid) {
    defects.push({ category: "UNSUPPORTED_CONCLUSION", description: `Conclusions not generated by engine: [${unsupportedResult.unsupportedConclusions.join(", ")}]` });
  }

  return {
    isValid: defects.length === 0,
    defects,
  };
}
