/**
 * P10-07: Unsupported Conclusion Blocker.
 * 
 * Ensures the legal memo does not contain any conclusions that were not 
 * explicitly generated and supported by the deterministic engine.
 * Prevents LLM hallucination of legal outcomes.
 */

export type MemoConclusion = {
  conclusionId: string;
  text: string;
};

export type BlockerResult = {
  isValid: boolean;
  unsupportedConclusions: string[];
};

/**
 * Validates that all conclusions in the memo exist in the engine's supported list.
 */
export function blockUnsupportedConclusions(
  memoConclusions: readonly MemoConclusion[],
  supportedConclusionIds: readonly string[]
): BlockerResult {
  const supportedSet = new Set(supportedConclusionIds);
  const unsupportedConclusions: string[] = [];

  for (const con of memoConclusions) {
    if (!supportedSet.has(con.conclusionId)) {
      unsupportedConclusions.push(con.conclusionId);
    }
  }

  return {
    isValid: unsupportedConclusions.length === 0,
    unsupportedConclusions,
  };
}

/**
 * Hard fail-closed guard. Throws an error if unsupported conclusions are present.
 */
export function assertNoUnsupportedConclusions(
  memoConclusions: readonly MemoConclusion[],
  supportedConclusionIds: readonly string[]
): void {
  const result = blockUnsupportedConclusions(memoConclusions, supportedConclusionIds);
  if (!result.isValid) {
    throw new Error(`Unsupported Conclusion Violation: The following conclusions were not generated by the engine: [${result.unsupportedConclusions.join(", ")}]`);
  }
}
