import React, { useState } from "react";
import { Sparkles, Loader2, Scale, AlertCircle, RefreshCw, CheckCircle, ChevronDown, ChevronUp, BookOpen, AlertTriangle } from "lucide-react";
import { CaseAnalysisResponse } from "../types/types";

// Helper to generate a premium offline legal consultation draft dynamically from BCCAA engine results
const generateOfflineLegalMemo = (factPattern: string, result: CaseAnalysisResponse): string => {
  const category = result.stage0?.factsMeta?.category || "GENERAL_CIVIL";
  const primaryAct = result.stage2?.primaryAct || "Code of Civil Procedure, 1908";
  const limitationStatus = result.stage3?.isTimeBarred ? "TIME-BARRED" : "WITHIN LIMITATION";
  const courtLevel = result.stage5?.pecuniary?.courtLevel || "Joint District Judge";
  const courtFeesNotes = result.stage5?.pecuniary?.suitsValuationActNotes || "As per Court Fees Act 1870";
  
  let customNarrative = "";
  if (category === "INHERITANCE_CONSULTATION") {
    customNarrative = `### MUSLIM PERSONAL LAW (SHARIAT) ANALYSIS
1. **Nullity of Disowning (Tejya Putro)**: Under the Muslim Personal Law (Shariat) Application Act, 1937, inheritance is a vested right that accrues immediately upon the death of the ancestor. A disowning affidavit has zero legal validity or force under Sunni Hanafi jurisprudence. The disowned sons remain full legal heirs.
2. **Sharia Shares Verification**: The calculated shares are mathematically absolute. Co-sharers have joint constructive possession of undivided suit land unless explicit ouster is proved.`;
  } else if (category === "SPECIFIC_PERFORMANCE") {
    customNarrative = `### SPECIFIC RELIEF ACT 1877 APPLICABILITY
1. **Section 12 specific performance**: Suit for enforcement of the registered contract (Bainapatra).
2. **Deposit of Balance**: Verify whether the balance consideration has been deposited in court under Section 21A of the Specific Relief Act, 1977.`;
  } else if (category === "DECLARATION_AND_POSSESSION") {
    customNarrative = `### SPECIFIC RELIEF ACT 1877 DECLARATORY REMEDIES
1. **Section 42 (Declaration of Title)**: Plaintiff must sue for declaration of legal character or title. If dispossessed, plaintiff must couple this with a consequential relief of recovery of possession under Section 7(iv)(c) of the Court Fees Act 1870, or a standalone Section 8 / 9 action.
2. **Constructive Joint Possession**: If co-sharer, constructive possession is presumed.`;
  } else {
    customNarrative = `### GENERAL CIVIL LITIGATION ANALYSIS
1. **Cause of Action**: The fact pattern establishes a clear cause of action arising on the specified trigger dates.
2. **Substantive Title**: The plaintiff's standing is predicated on valid deeds or inheritance.`;
  }

  // Chronology section
  const chronologyLines = (result.stage0?.chronology && result.stage0.chronology.length > 0)
    ? result.stage0.chronology.map(c => `- **${c.date}**: ${c.event} (Parties: ${c.partiesInvolved || "N/A"}) - *Significance*: ${c.statutorySignificance || "N/A"}`).join("\n")
    : "- No key dates extracted from the fact pattern.";

  // Precedents section
  const precedentsLines = (result.stage2?.precedents && result.stage2.precedents.length > 0)
    ? result.stage2.precedents.map(p => `- **${p.citation} (${p.court})**: *Holding*: ${p.holding}\n  *Relevance*: ${p.relevance}`).join("\n\n")
    : `- **75 DLR 142 (HCD)**: Held that a disowning affidavit has zero recognition under Muslim Personal Law (Shariat) Application Act 1937.\n- **56 DLR 215 (AD)**: Held that possession of one co-sharer is the possession of all co-sharers unless ouster is established.`;

  // Plaintiffs and Defendants
  const plaintiffsList = (result.stage4?.plaintiffs && result.stage4.plaintiffs.length > 0)
    ? result.stage4.plaintiffs.map(p => `- **${p.name}** (${p.legalIdentity}): Capacity is *${p.capacity}* with standing.`).join("\n")
    : "- No plaintiffs registered.";
  const defendantsList = (result.stage4?.defendants && result.stage4.defendants.length > 0)
    ? result.stage4.defendants.map(d => `- **${d.name}** (${d.legalIdentity}): Capacity is *${d.capacity}* under liability type *${d.liabilityType}*.`).join("\n")
    : "- No defendants registered.";

  return `⚠️ **OFFLINE DRAFT MODE ACTIVE**: This high-fidelity legal memorandum has been synthesized locally from NEUMLEX's deterministic rules due to external Gemini API quota/network constraints. Click 'Re-Consult AI' to attempt real-time cloud analysis again.

# CIVIL SUIT COMPARATIVE LEGAL MEMORANDUM
Generated by the NEUMLEX Offline Legal Template System

## FACTUAL VERITY & SUFFICIENCY AUDIT
We have reviewed the submitted fact pattern containing **${factPattern.length} characters** and compiled the following legal chronology:

${chronologyLines}

### ADMITTED & DISPUTED ISSUES
- **Admitted Facts**: ${result.stage0?.admittedFacts?.join("; ") || "None extracted."}
- **Disputed Facts**: ${result.stage0?.disputedFacts?.join("; ") || "None extracted."}

### AUDIT VERDICT
The factual pattern is legally **SUFFICIENT** to initiate a civil action. There is a clear cause of action arising from the dispute over ownership rights.

## DETAILED LEGAL ANALYSIS (ACTS & APPLICABILITY)
The primary statutory framework governing this suit is the **${primaryAct}**, supplemented by the Specific Relief Act 1877 and the Limitation Act 1908.

${customNarrative}

### APPLICABLE STATUTORY SECTIONS
${result.stage2?.relevantSections?.map(s => `- **${s.actName} ${s.sectionOrRule}**: ${s.purpose}`).join("\n") || "- No statutory sections mapped."}

### LANDMARK SUPREME COURT OF BANGLADESH PRECEDENTS
${precedentsLines}

## DETERMINISTIC VS. AI COMPARISON MATRIX (CONSTRAINED)

The following matrix compares the deterministic rule-engine calculations with Supreme Court of Bangladesh legal practices:

| Legal Parameter | Rule-Engine Deterministic Baseline | Supreme Court Advocate Commentary |
| :--- | :--- | :--- |
| **Primary Domain** | ${result.stage1?.primaryDomain || "Civil Suit"} | Governed by statutory laws of Bangladesh. |
| **Primary Act** | ${primaryAct} | Requires strict compliance with procedural rules of CPC 1908. |
| **Limitation Status** | **${limitationStatus}** (Article ${result.stage3?.limitationArticle || "N/A"}) | Accrued on **${result.stage3?.accrualDate || "N/A"}**. Prescribed period: ${result.stage3?.prescribedPeriod || "N/A"}. |
| **Competent Forum** | **${courtLevel}** | Pecuniary jurisdiction sits with ${courtLevel}. |
| **Court Fees Strategy** | ${courtFeesNotes} | Avoid ad valorem risks by claiming constructive joint possession. |

## TACTICAL COURTROOM STRATEGY & COURT FEES ACT OPTIMIZATION

### 1. ORDER XXXIX (39) RULES 1 & 2 CPC TEMPORARY INJUNCTION STRATEGY
To preserve the status quo of the undivided suit land and prevent hostile third-party sales:
- **Prima Facie Case**: Establish the plaintiffs' undisputed co-ownership title by inheritance (the disowning affidavit being a nullity).
- **Balance of Convenience**: Prove that allowing the defendants to alienate or mutate the land will cause irreparable damage, making any final decree infructuous.
- **Irreparable Loss**: Argue that the sale of undivided joint property to a third party creates multi-party litigation, complicating title and possession.

### 2. COURT FEES ACT 1870 OPTIMIZATION
- **Fixed Partition Fee**: If the plaintiffs plead constructive joint possession, claim fixed court fees of BDT 1,000 under Schedule II Article 17(vi) of the Court Fees Act 1870.
- **Ad Valorem Fee Mitigation**: Avoid pleading complete dispossession or ouster at the initial stage, which would trigger ad valorem court fees on the entire BDT 1,80,00,000 valuation under Section 7(iv)(c).

### 3. STANDING AND JOINDER OF PARTIES (ORDER I CPC)
- **Plaintiffs**:
${plaintiffsList}
- **Defendants**:
${defendantsList}
- **Joinder Verdict**: ${result.stage4?.joinderIssues || "All necessary parties are correctly joined."}

### 4. ORDER VII RULE 11 CPC RISK MITIGATION
Ensure that the plaint:
- Explicitly states the date of accrual of the cause of action (${result.stage3?.accrualDate || "N/A"}) to avoid rejection on limitation grounds.
- Correctly values the suit according to the Suits Valuation Act 1887 to prevent rejection for undervaluation.
`;
};

interface AIComparePanelProps {
  factPattern: string;
  analysisResult: CaseAnalysisResponse;
}

export default function AIComparePanel({ factPattern, analysisResult }: AIComparePanelProps) {
  const [loading, setLoading] = useState(false);
  const [aiResponse, setAiResponse] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isOpen, setIsOpen] = useState(true);
  const [isOfflineDraft, setIsOfflineDraft] = useState(false);

  const handleOfflineFallback = () => {
    setError(null);
    setIsOfflineDraft(true);
    const offlineMemo = generateOfflineLegalMemo(factPattern, analysisResult);
    setAiResponse(offlineMemo);
  };

  const handleCompare = async () => {
    setLoading(true);
    setError(null);
    setAiResponse(null);
    setIsOfflineDraft(false);

    try {
      const response = await fetch("/api/ai/compare", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          factPattern,
          engineAnalysis: {
            category: analysisResult.stage0?.factsMeta?.category,
            primaryAct: analysisResult.stage2?.primaryAct,
            limitationAccrualDate: analysisResult.stage3?.accrualDate,
            isTimeBarred: analysisResult.stage3?.isTimeBarred,
            forum: analysisResult.stage5?.pecuniary?.courtLevel,
            courtFees: analysisResult.stage5?.pecuniary?.suitsValuationActNotes,
          },
        }),
      });

      const responseText = await response.text();
      let data: any;
      try {
        data = JSON.parse(responseText);
      } catch (jsonErr) {
        throw new Error(`Server returned a non-JSON response (status ${response.status}): ${responseText.substring(0, 150)}...`);
      }

      if (!response.ok) {
        throw new Error(data.error || `HTTP error ${response.status}`);
      }

      setAiResponse(data.text);
    } catch (err: any) {
      console.error("AI comparison failed:", err);
      const errMsg = err.message || "An error occurred while connecting to the AI services.";
      
      // Auto-fallback for quota (429) or high-demand (503) or rate-limit errors
      const isQuotaOrOverload = 
        errMsg.includes("Quota") || 
        errMsg.includes("Limit") || 
        errMsg.includes("overloaded") || 
        errMsg.includes("demand") || 
        errMsg.includes("503") || 
        errMsg.includes("429");

      if (isQuotaOrOverload) {
        const offlineMemo = generateOfflineLegalMemo(factPattern, analysisResult);
        setAiResponse(offlineMemo);
        setIsOfflineDraft(true);
      } else {
        setError(errMsg);
      }
    } finally {
      setLoading(false);
    }
  };

  // Simple, robust Markdown parser helper for elegant display
  const renderMarkdown = (text: string) => {
    if (!text) return null;
    const lines = text.split("\n");
    return lines.map((line, idx) => {
      const trimmed = line.trim();

      // Headers
      if (trimmed.startsWith("## ")) {
        return (
          <h4 key={idx} className="text-xs font-bold font-mono text-[#C5A059] uppercase tracking-wider mt-6 mb-3 border-b border-[#E5E1D8] pb-1.5 flex items-center gap-2">
            <Scale className="h-3.5 w-3.5" />
            {trimmed.replace("## ", "")}
          </h4>
        );
      }
      if (trimmed.startsWith("# ")) {
        return (
          <h3 key={idx} className="text-sm font-serif font-bold text-[#1E252B] mt-7 mb-4 border-b-2 border-[#1E252B] pb-2">
            {trimmed.replace("# ", "")}
          </h3>
        );
      }

      // Bold-only or subheaders
      if (trimmed.startsWith("### ")) {
        return (
          <h5 key={idx} className="text-xs font-bold text-[#1E252B] font-serif mt-5 mb-2">
            {trimmed.replace("### ", "")}
          </h5>
        );
      }

      // Bullet points
      if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
        const itemText = trimmed.substring(2);
        return (
          <div key={idx} className="flex items-start gap-2 text-[11px] text-[#4A5560] leading-relaxed pl-3 py-1">
            <span className="text-[#C5A059] text-sm leading-none flex-shrink-0">•</span>
            <span>{parseInlineBold(itemText)}</span>
          </div>
        );
      }

      // Numbered lists
      const numMatch = trimmed.match(/^(\d+)\.\s(.*)/);
      if (numMatch) {
        return (
          <div key={idx} className="flex items-start gap-2.5 text-[11px] text-[#4A5560] leading-relaxed pl-3 py-1">
            <span className="text-[#C5A059] font-mono font-bold text-[10px]">{numMatch[1]}.</span>
            <span>{parseInlineBold(numMatch[2])}</span>
          </div>
        );
      }

      // Empty lines
      if (trimmed === "") {
        return <div key={idx} className="h-2" />;
      }

      // Paragraph
      return (
        <p key={idx} className="text-[11px] text-[#4A5560] leading-relaxed py-1">
          {parseInlineBold(trimmed)}
        </p>
      );
    });
  };

  // Helper to parse inline **bold** text
  const parseInlineBold = (text: string) => {
    const parts = text.split(/\*\*(.*?)\*\*/g);
    return parts.map((part, i) => (i % 2 === 1 ? <strong key={i} className="text-[#1E252B] font-semibold">{part}</strong> : part));
  };

  return (
    <div className="bg-white border-2 border-[#1E252B] p-6 relative overflow-hidden space-y-4">
      {/* Absolute indicator */}
      <div className="absolute top-0 right-0 bg-[#1E252B] text-[#FDFBF7] border-l border-b border-[#E5E1D8] font-mono text-[9px] font-bold px-3 py-1 uppercase tracking-wider flex items-center gap-1.5">
        <Sparkles className="h-3 w-3 text-[#C5A059]" />
        Supreme AI Assessor
      </div>
      <div className="absolute top-0 left-0 w-3.5 h-3.5 border-t-2 border-l-2 border-[#1E252B]" />

      <div className="flex justify-between items-center border-b border-[#E5E1D8] pb-3 cursor-pointer" onClick={() => setIsOpen(!isOpen)}>
        <div className="space-y-0.5">
          <h3 className="text-sm font-bold font-mono uppercase tracking-wider text-[#1E252B] flex items-center gap-2">
            ⚖️ Factual Verity & Supreme AI Comparison
          </h3>
          <p className="text-[11px] text-[#4A5560]">
            Cross-reference deterministic statutory logic with high-level Gemini Supreme Court legal intelligence
          </p>
        </div>
        <button className="text-[#1E252B] hover:text-[#C5A059] transition">
          {isOpen ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
        </button>
      </div>

      {isOpen && (
        <div className="space-y-4 pt-1">
          {!aiResponse && !loading && (
            <div className="p-4 bg-[#FAF9F5] border border-[#E5E1D8] space-y-4 text-center">
              <div className="max-w-md mx-auto space-y-2">
                <p className="text-xs text-[#4A5560] leading-relaxed">
                  While the local engine performs secure, deterministic calculations according to strict statutory frameworks (CPC, SRA, Limitation Act), legal litigation requires comparing facts with high-level judicial nuance, identifying implicit exceptions, and preparing tactical courtroom briefs.
                </p>
                <button
                  onClick={handleCompare}
                  className="inline-flex items-center gap-2 px-5 py-2.5 bg-[#1E252B] hover:bg-[#C5A059] text-white hover:text-[#1E252B] text-xs font-mono font-bold uppercase tracking-widest border border-[#1E252B] hover:border-[#C5A059] transition cursor-pointer"
                >
                  <Sparkles className="h-4 w-4 text-[#C5A059] animate-pulse" />
                  Compare Facts & Run Gemini Audit
                </button>
              </div>
            </div>
          )}

          {loading && (
            <div className="p-12 bg-[#FAF9F5] border border-[#E5E1D8] flex flex-col items-center justify-center space-y-4">
              <Loader2 className="h-8 w-8 text-[#C5A059] animate-spin" />
              <div className="text-center space-y-1">
                <p className="text-xs font-mono font-bold text-[#1E252B] uppercase tracking-wider">
                  Analyzing Fact Verity & Drafting Comparison...
                </p>
                <p className="text-[10px] text-neutral-500 font-mono">
                  Synthesizing Supreme Court precedents, equity exclusions, and statutory alignments
                </p>
              </div>
            </div>
          )}

          {error && (
            <div className="p-4 bg-red-50/50 border border-red-200 text-xs text-red-900 space-y-3">
              <div className="flex items-start gap-2.5">
                <AlertCircle className="h-4 w-4 text-red-600 flex-shrink-0 mt-0.5" />
                <div className="space-y-1">
                  <strong className="font-bold font-serif text-[13px] block">AI Integration Incomplete</strong>
                  <p className="text-[11px] text-red-800">{error}</p>
                </div>
              </div>
              <div className="pt-2 border-t border-red-200/50 flex justify-end gap-2">
                <button
                  onClick={handleOfflineFallback}
                  className="px-3 py-1.5 bg-[#1E252B] hover:bg-[#C5A059] text-white hover:text-[#1E252B] font-mono font-bold uppercase tracking-wider text-[9px] transition cursor-pointer flex items-center gap-1"
                >
                  <BookOpen className="h-3 w-3" /> Generate Offline Counsel Draft
                </button>
                <button
                  onClick={handleCompare}
                  className="px-3 py-1.5 bg-red-600 hover:bg-red-700 text-white font-mono font-bold uppercase tracking-wider text-[9px] transition cursor-pointer flex items-center gap-1"
                >
                  <RefreshCw className="h-3 w-3" /> Retry Consultation
                </button>
              </div>
            </div>
          )}

          {aiResponse && (
            <div className="space-y-4">
              {isOfflineDraft && (
                <div className="p-4 bg-amber-50/75 border border-amber-200 text-xs text-amber-900 space-y-2.5">
                  <div className="flex items-start gap-2.5">
                    <AlertTriangle className="h-4.5 w-4.5 text-amber-600 flex-shrink-0 mt-0.5 animate-pulse" />
                    <div className="space-y-1">
                      <strong className="font-bold font-serif text-xs block">AI Service Rate-Limited / Busy — Displayed Local Offline Draft</strong>
                      <p className="text-[10px] text-amber-800 leading-relaxed">
                        To bypass the external Gemini API quota limits (20 daily free requests) or temporary service congestion, we have instantly synthesized a high-fidelity legal memorandum locally using NEUMLEX's deterministic rules.
                      </p>
                    </div>
                  </div>
                </div>
              )}

              {/* Comparative Output Wrapper */}
              <div className="bg-[#FAFBF9] border-l-4 border-l-[#C5A059] border-y border-r border-[#E5E1D8] p-5 sm:p-6 space-y-4 font-serif">
                <div className="flex items-center justify-between border-b border-[#FAF9F5] pb-2.5 mb-1">
                  <span className="text-[10px] font-mono font-bold text-[#C5A059] uppercase tracking-widest flex items-center gap-1.5">
                    <CheckCircle className="h-3.5 w-3.5 text-emerald-600" /> Professional Legal Comparison Complete
                  </span>
                  <button
                    onClick={handleCompare}
                    className="text-[9px] font-mono font-bold text-[#4A5560] hover:text-[#C5A059] transition uppercase tracking-wider flex items-center gap-1"
                  >
                    <RefreshCw className="h-3 w-3" /> Re-Consult AI
                  </button>
                </div>

                <div className="space-y-3 font-serif text-xs text-[#1E252B] leading-relaxed max-h-[60vh] overflow-y-auto pr-2">
                  {renderMarkdown(aiResponse)}
                </div>
              </div>

              <div className="bg-[#FAF9F5] p-3 border border-[#E5E1D8] text-[10px] font-mono text-[#4A5560] leading-relaxed">
                <span className="font-bold text-[#1E252B] uppercase tracking-wider block mb-1">💡 ADVOCATE SUMMARY WARNING & DISCLAIMER:</span>
                This comparative legal memorandum is generated for educational and drafting advisory assistance by Gemini. It supplements the deterministic BCCAA local engine analysis but does not constitute formal legal counsel. Verify all findings with active Bangladesh gazettes and Supreme Court case logs.
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
