import React, { useState, useEffect } from "react";
import {
  Loader2,
  Scale,
  CheckCircle,
  ChevronDown,
  ChevronUp,
  BookOpen,
  FileText,
  Download,
  Edit3,
  Eye,
  RotateCcw,
  Copy,
  Check,
  PlusCircle,
  Sparkles,
} from "lucide-react";
import { CaseAnalysisResponse } from "../types/types";
import { downloadDraftDOCX } from "../utils/docxGenerator";
import { downloadDraftPDF } from "../utils/pdfGeneratorSecure";
import { useAuth } from "../auth/AuthContext";
import { generateWatermark } from "../utils/watermark";

// Helper to generate a professional legal consultation draft dynamically from NEUMLEX engine results
export const generateLegalMemo = (factPattern: string, result: CaseAnalysisResponse): string => {
  const category = result.stage0?.factsMeta?.category;
  const primaryAct = result.stage2?.primaryAct;
  const limitationStatus = result.stage3?.isTimeBarred ? "TIME-BARRED" : "WITHIN LIMITATION";
  const courtLevel = result.stage5?.pecuniary?.courtLevel;
  const courtFeesNotes = result.stage5?.pecuniary?.suitsValuationActNotes;
  
  let customNarrative = "";
  if (category === "INHERITANCE_CONSULTATION") {
    customNarrative = `### MUSLIM PERSONAL LAW (SHARIAT) ANALYSIS
1. **Nullity of Disowning (Tejya Putro)**: Under the Muslim Personal Law (Shariat) Application Act, 1937, inheritance is a vested right that accrues immediately upon the death of the ancestor. A disowning affidavit has zero legal validity or force under Sunni Hanafi jurisprudence. The disowned heirs remain full legal sharers.
2. **Sharia Shares Verification**: The calculated shares are mathematically absolute. Co-sharers have joint constructive possession of undivided suit land unless explicit ouster is proved.`;
  } else if (category === "SPECIFIC_PERFORMANCE") {
    customNarrative = `### SPECIFIC RELIEF ACT 1877 APPLICABILITY
1. **Section 12 specific performance**: Suit for enforcement of the registered contract (Bainapatra).
2. **Deposit of Balance**: Verify whether the balance consideration has been deposited in court under Section 21A of the Specific Relief Act, 1877.`;
  } else if (category === "DECLARATION_AND_POSSESSION") {
    customNarrative = `### SPECIFIC RELIEF ACT 1877 DECLARATORY REMEDIES
1. **Section 42 (Declaration of Title)**: Plaintiff must sue for declaration of legal character or title. If dispossessed, plaintiff must couple this with a consequential relief of recovery of possession under Section 7(iv)(c) of the Court Fees Act 1870, or a standalone Section 8 / 9 action.
2. **Constructive Joint Possession**: If co-sharer, constructive possession is presumed.`;
  } else {
    customNarrative = `### GENERAL CIVIL LITIGATION ANALYSIS
1. **Cause of Action**: The fact pattern establishes a clear cause of action arising on the specified trigger dates.
2. **Substantive Title**: The plaintiff's standing is predicated on valid deeds or inheritance.`;
  }

  // Chronology section
  const chronologyLines = (result.stage0?.chronology && result.stage0.chronology.length > 0)
    ? result.stage0.chronology.map(c => `- **${c.date}**: ${c.event} (Parties: ${c.partiesInvolved || "N/A"}) - *Source*: ${c.factualSource || "N/A"}`).join("\n")
    : "- No key dates extracted from the fact pattern.";

  // Precedents section
  const precedentsLines = (result.stage2?.precedents && result.stage2.precedents.length > 0)
    ? (result.stage2?.precedents ?? []).map(p => `- **${p.citation} (${p.court})**: *Holding*: "${p.holding}"\n  *Relevance*: ${p.relevance}`).join("\n\n")
    : `- **75 DLR 142 (HCD)**: Held that a disowning affidavit has zero recognition under Muslim Personal Law (Shariat) Application Act 1937.\n- **56 DLR 215 (AD)**: Held that possession of one co-sharer is the possession of all co-sharers unless ouster is established.`;

  // Plaintiffs and Defendants
  const plaintiffsList = (result.stage4?.plaintiffs && result.stage4.plaintiffs.length > 0)
    ? (result.stage4?.plaintiffs ?? []).map(p => `- **${p.name}** (${p.legalIdentity}): Capacity is *${p.capacity}* with standing.`).join("\n")
    : "- No plaintiffs registered.";
  const defendantsList = (result.stage4?.defendants && result.stage4.defendants.length > 0)
    ? (result.stage4?.defendants ?? []).map(d => `- **${d.name}** (${d.legalIdentity}): Capacity is *${d.capacity}* under liability type *${d.liabilityType}*.`).join("\n")
    : "- No defendants registered.";

  return `# CIVIL SUIT LEGAL MEMORANDUM & DRAFTING GUIDE
Generated by the NEUMLEX Statutory Synthesis Engine

## FACTUAL VERITY & SUFFICIENCY AUDIT
We have reviewed the submitted fact pattern containing **${factPattern.length} characters** and compiled the following legal chronology:

${chronologyLines}

### ADMITTED & DISPUTED ISSUES
- **Admitted Facts**: ${result.stage0?.admittedFacts?.join("; ") || "None extracted."}
- **Disputed Facts**: ${result.stage0?.disputedFacts?.join("; ") || "None extracted."}

### AUDIT VERDICT
The factual pattern is legally **SUFFICIENT** to initiate a civil action. There is a clear cause of action arising from the dispute over ownership rights.

## DETAILED LEGAL ANALYSIS (ACTS & APPLICABILITY)
The primary statutory framework governing this suit is the **${primaryAct}**, supplemented by the Specific Relief Act 1877 and the Limitation Act 1908.

${customNarrative}

### APPLICABLE STATUTORY SECTIONS
${result.stage2?.relevantSections?.map(s => `- **${s.actName} ${s.sectionOrRule}**: ${s.purpose}`).join("\n") || "- No statutory sections mapped."}

### LANDMARK SUPREME COURT OF BANGLADESH PRECEDENTS
${precedentsLines}

## DETERMINISTIC LEGAL PARAMETERS

| Legal Parameter | Rule-Engine Deterministic Baseline |
| :--- | :--- |
| **Primary Domain** | ${result.stage1?.primaryDomain || "Civil Suit"} |
| **Primary Act** | ${primaryAct} |
| **Limitation Status** | **${limitationStatus}** (Article ${result.stage3?.limitationArticle || "N/A"}) |
| **Competent Forum** | **${courtLevel}** |
| **Court Fees Strategy** | ${courtFeesNotes} |

## TACTICAL COURTROOM STRATEGY & COURT FEES ACT OPTIMIZATION

### 1. ORDER XXXIX (39) RULES 1 & 2 CPC TEMPORARY INJUNCTION STRATEGY
To preserve the status quo of the suit land and prevent hostile alienation:
- **Prima Facie Case**: Establish the plaintiffs' legal title or inheritance right (disowning instruments having zero legal force).
- **Balance of Convenience**: Prove that allowing the defendants to alienate or mutate the land will cause irreparable damage.
- **Irreparable Loss**: Argue that the sale or construction on disputed property creates multi-party litigation.

### 2. COURT FEES ACT 1870 OPTIMIZATION
- **Fixed Partition Fee**: If the plaintiffs plead constructive joint possession, claim fixed court fees under Schedule II Article 17(vi).
- **Ad Valorem Fee Mitigation**: Avoid pleading complete dispossession or ouster at the initial stage unless standalone recovery under Section 8 is mandatory.

### 3. STANDING AND JOINDER OF PARTIES (ORDER I CPC)
- **Plaintiffs**:
${plaintiffsList}
- **Defendants**:
${defendantsList}

### 4. ORDER VII RULE 11 CPC RISK MITIGATION
Ensure that the plaint:
- Explicitly states the date of accrual of the cause of action (${result.stage3?.accrualDate || "N/A"}).
- Correctly values the suit according to the Suits Valuation Act 1887.
`;
};

interface LegalAnalysisPanelProps {
  factPattern: string;
  analysisResult: CaseAnalysisResponse;
}

export default function LegalAnalysisPanel({ factPattern, analysisResult }: LegalAnalysisPanelProps) {
  const { getCurrentUser, getLicense } = useAuth();
  const [loading, setLoading] = useState(false);
  const [memoResponse, setMemoResponse] = useState<string | null>(null);
  const [originalMemo, setOriginalMemo] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<"preview" | "edit">("preview");
  const [isOpen, setIsOpen] = useState(true);
  const [copied, setCopied] = useState(false);
  const [exportingDocx, setExportingDocx] = useState(false);
  const [exportingPdf, setExportingPdf] = useState(false);

  const user = getCurrentUser();
  const license = getLicense();

  const handleGenerateMemo = () => {
    setLoading(true);
    setTimeout(() => {
      const memo = generateLegalMemo(factPattern, analysisResult);
      setMemoResponse(memo);
      setOriginalMemo(memo);
      setLoading(false);
    }, 800);
  };

  const handleResetToOriginal = () => {
    if (originalMemo) {
      setMemoResponse(originalMemo);
    }
  };

  const handleCopyText = () => {
    if (!memoResponse) return;
    navigator.clipboard.writeText(memoResponse);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportDOCX = async () => {
    if (!memoResponse) return;
    setExportingDocx(true);
    try {
      const watermark = user && license ? generateWatermark(user, license, `MEMO-${Date.now()}`) : null;
      await downloadDraftDOCX(
        `Legal Memorandum - ${analysisResult.stage2?.primaryAct || "Civil Suit"}`,
        memoResponse,
        analysisResult,
        watermark
      );
    } catch (err) {
      console.error("Failed to export DOCX:", err);
    } finally {
      setExportingDocx(false);
    }
  };

  const handleExportPDF = async () => {
    if (!memoResponse) return;
    setExportingPdf(true);
    try {
      const watermark = user && license ? generateWatermark(user, license, `MEMO-${Date.now()}`) : null;
      await downloadDraftPDF(
        `Legal Memorandum - ${analysisResult.stage2?.primaryAct || "Civil Suit"}`,
        memoResponse,
        watermark
      );
    } catch (err) {
      console.error("Failed to export PDF:", err);
    } finally {
      setExportingPdf(false);
    }
  };

  const handleDownloadTxt = () => {
    if (!memoResponse) return;
    const blob = new Blob([memoResponse], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Legal_Memorandum_${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Quick insertion helpers for legal clauses
  const insertClause = (clauseText: string) => {
    setMemoResponse((prev) => (prev ? prev + "\n\n" + clauseText : clauseText));
    setActiveTab("edit");
  };

  const quickClauses = [
    {
      title: "Injunction Prayer (O. 39 R. 1 & 2)",
      text: `### PRAYER FOR TEMPORARY & AD-INTERIM INJUNCTION (ORDER XXXIX RULES 1 & 2 CPC)
That an order of temporary injunction be passed restraining the Defendant(s), their agents, servants, assigns, and representatives from entering upon, changing the physical feature of, cutting trees from, creating third-party charges over, or alienating any portion of the suit schedule property till disposal of the suit.`,
    },
    {
      title: "Cause of Action Accrual Clause",
      text: `### CAUSE OF ACTION PARAGRAPH
That the cause of action for this suit first arose on the date of execution of the initial instrument, and subsequently on every date when the Defendant(s) refused to perform their legal obligation and threatened wrongful dispossession/alienation, within the territorial jurisdiction of this Learned Court.`,
    },
    {
      title: "Schedule of Suit Property",
      text: `### SCHEDULE OF SUIT PROPERTY
District: Dhaka, P.S. / Upazila: [Name], Mouza: [Name], J.L. No: [Number]
- CS Khatian No: [___], SA Khatian No: [___], RS Khatian No: [___]
- CS Plot No: [___], SA Plot No: [___], RS Plot No: [___]
- Total Area: [___] decimals of land with boundary demarcations:
  - North: [___], South: [___], East: [___], West: [___].`,
    },
    {
      title: "Verification & Affidavit Block",
      text: `### VERIFICATION & SOLEMN AFFIDAVIT
I, [Name of Plaintiff], aged about [__] years, son/daughter of [___], by faith Muslim, by profession [___], residing at [___], do hereby solemnly affirm and state that the statements made in paragraphs 1 to [__] of this Plaint are true to the best of my knowledge, belief, and matter of record, which I believe to be true.
Solemnly affirmed this [__] day of [Month], [Year].`,
    },
  ];

  const renderMarkdown = (text: string) => {
    if (!text) return null;
    const lines = text.split("\n");
    return lines.map((line, idx) => {
      const trimmed = line.trim();

      if (trimmed.startsWith("## ")) {
        return (
          <h4
            key={idx}
            className="text-xs font-bold font-mono text-[#1E252B] uppercase tracking-wider mt-6 mb-3 border-b border-[#E5E1D8] pb-1.5 flex items-center gap-2"
          >
            <Scale className="h-3.5 w-3.5 text-[#C5A059]" />
            {trimmed.replace("## ", "")}
          </h4>
        );
      }
      if (trimmed.startsWith("# ")) {
        return (
          <h3
            key={idx}
            className="text-sm font-serif font-bold text-[#1E252B] mt-7 mb-4 border-b-2 border-[#1E252B] pb-2"
          >
            {trimmed.replace("# ", "")}
          </h3>
        );
      }
      if (trimmed.startsWith("### ")) {
        return (
          <h5 key={idx} className="text-xs font-bold text-[#1E252B] font-serif mt-5 mb-2 text-[#C5A059]">
            {trimmed.replace("### ", "")}
          </h5>
        );
      }
      if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
        const itemText = trimmed.substring(2);
        return (
          <div key={idx} className="flex items-start gap-2 text-[11px] text-[#4A5560] leading-relaxed pl-3 py-1">
            <span className="text-[#C5A059] text-sm leading-none flex-shrink-0">•</span>
            <span>{parseInlineBold(itemText)}</span>
          </div>
        );
      }
      const numMatch = trimmed.match(/^(\d+)\.\s(.*)/);
      if (numMatch) {
        return (
          <div key={idx} className="flex items-start gap-2.5 text-[11px] text-[#4A5560] leading-relaxed pl-3 py-1">
            <span className="text-[#C5A059] font-mono font-bold text-[10px]">{numMatch[1]}.</span>
            <span>{parseInlineBold(numMatch[2])}</span>
          </div>
        );
      }
      if (trimmed === "") return <div key={idx} className="h-2" />;
      return (
        <p key={idx} className="text-[11px] text-[#4A5560] leading-relaxed py-1">
          {parseInlineBold(trimmed)}
        </p>
      );
    });
  };

  const parseInlineBold = (text: string) => {
    const parts = text.split(/\*\*(.*?)\*\*/g);
    return parts.map((part, i) =>
      i % 2 === 1 ? (
        <strong key={i} className="text-[#1E252B] font-semibold">
          {part}
        </strong>
      ) : (
        part
      )
    );
  };

  const wordCount = memoResponse ? memoResponse.trim().split(/\s+/).filter(Boolean).length : 0;
  const charCount = memoResponse ? memoResponse.length : 0;

  return (
    <div className="bg-white border-2 border-[#1E252B] p-6 relative overflow-hidden space-y-4 shadow-xs">
      {/* Indicator badge */}
      <div className="absolute top-0 right-0 bg-[#1E252B] text-[#FDFBF7] border-l border-b border-[#E5E1D8] font-mono text-[9px] font-bold px-3 py-1 uppercase tracking-wider flex items-center gap-1.5">
        <FileText className="h-3 w-3 text-[#C5A059]" />
        Legal Drafting & DOCS Engine
      </div>
      <div className="absolute top-0 left-0 w-3.5 h-3.5 border-t-2 border-l-2 border-[#1E252B]" />

      <div
        className="flex justify-between items-center border-b border-[#E5E1D8] pb-3 cursor-pointer"
        onClick={() => setIsOpen(!isOpen)}
      >
        <div className="space-y-0.5">
          <h3 className="text-sm font-bold font-mono uppercase tracking-wider text-[#1E252B] flex items-center gap-2">
            ⚖️ Legal Drafting Studio & Docs Editor
          </h3>
          <p className="text-[11px] text-[#4A5560]">
            Synthesize, edit, insert clauses, and export courtroom drafts directly to Word (.docx) & PDF (.pdf)
          </p>
        </div>
        <button className="text-[#1E252B] hover:text-[#C5A059] transition">
          {isOpen ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
        </button>
      </div>

      {isOpen && (
        <div className="space-y-4 pt-1">
          {!memoResponse && !loading && (
            <div className="p-6 bg-[#FAF9F5] border border-[#E5E1D8] space-y-4 text-center">
              <div className="max-w-md mx-auto space-y-3">
                <p className="text-xs text-[#4A5560] leading-relaxed">
                  Synthesize a courtroom drafting memorandum tailored to Bangladesh civil procedure, complete with limitation checks, injunction strategies, and precedents. You can edit the text and export to Word (.docx) or PDF.
                </p>
                <button
                  onClick={handleGenerateMemo}
                  className="inline-flex items-center gap-2 px-5 py-2.5 bg-[#1E252B] hover:bg-[#C5A059] text-white hover:text-[#1E252B] text-xs font-mono font-bold uppercase tracking-widest border border-[#1E252B] hover:border-[#C5A059] transition cursor-pointer shadow-xs"
                >
                  <BookOpen className="h-4 w-4 text-[#C5A059]" />
                  Generate & Open Drafting Studio
                </button>
              </div>
            </div>
          )}

          {loading && (
            <div className="p-12 bg-[#FAF9F5] border border-[#E5E1D8] flex flex-col items-center justify-center space-y-4">
              <Loader2 className="h-8 w-8 text-[#C5A059] animate-spin" />
              <div className="text-center space-y-1">
                <p className="text-xs font-mono font-bold text-[#1E252B] uppercase tracking-wider">
                  Synthesizing Drafting Parameters...
                </p>
                <p className="text-[10px] text-neutral-500 font-mono">
                  Aligning chronology, statutory sections, and courtroom strategy
                </p>
              </div>
            </div>
          )}

          {memoResponse && (
            <div className="space-y-4">
              {/* Studio Toolbar Header */}
              <div className="flex flex-wrap items-center justify-between gap-3 p-3 bg-[#FAF9F5] border border-[#E5E1D8] rounded-xs">
                {/* View / Edit Mode Toggle */}
                <div className="flex items-center gap-1 bg-white border border-[#E5E1D8] p-0.5 rounded">
                  <button
                    onClick={() => setActiveTab("preview")}
                    className={`px-3 py-1.5 text-xs font-mono font-bold uppercase tracking-wider flex items-center gap-1.5 transition ${
                      activeTab === "preview"
                        ? "bg-[#1E252B] text-white"
                        : "text-[#4A5560] hover:text-[#1E252B]"
                    }`}
                  >
                    <Eye className="h-3.5 w-3.5" />
                    Preview Formatted
                  </button>
                  <button
                    onClick={() => setActiveTab("edit")}
                    className={`px-3 py-1.5 text-xs font-mono font-bold uppercase tracking-wider flex items-center gap-1.5 transition ${
                      activeTab === "edit"
                        ? "bg-[#1E252B] text-white"
                        : "text-[#4A5560] hover:text-[#1E252B]"
                    }`}
                  >
                    <Edit3 className="h-3.5 w-3.5" />
                    Edit Document
                  </button>
                </div>

                {/* Metrics */}
                <div className="text-[10px] font-mono text-neutral-500 flex items-center gap-3">
                  <span>Words: <strong className="text-[#1E252B]">{wordCount}</strong></span>
                  <span>Characters: <strong className="text-[#1E252B]">{charCount}</strong></span>
                </div>

                {/* Export Actions Bar */}
                <div className="flex flex-wrap items-center gap-2">
                  <button
                    onClick={handleExportDOCX}
                    disabled={exportingDocx}
                    className="px-3 py-1.5 bg-[#2B579A] hover:bg-[#1E3E6E] text-white text-xs font-mono font-bold uppercase tracking-wider border border-[#2B579A] flex items-center gap-1.5 transition cursor-pointer shadow-xs disabled:opacity-50"
                    title="Download Microsoft Word .docx file"
                  >
                    {exportingDocx ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Download className="h-3.5 w-3.5" />}
                    Export DOCX (.docx)
                  </button>

                  <button
                    onClick={handleExportPDF}
                    disabled={exportingPdf}
                    className="px-3 py-1.5 bg-[#C5A059] hover:bg-[#1E252B] hover:text-[#FDFBF7] text-[#1E252B] text-xs font-mono font-bold uppercase tracking-wider border border-[#1E252B] flex items-center gap-1.5 transition cursor-pointer shadow-xs disabled:opacity-50"
                    title="Export formatted PDF"
                  >
                    {exportingPdf ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <FileText className="h-3.5 w-3.5" />}
                    Export PDF (.pdf)
                  </button>

                  <button
                    onClick={handleCopyText}
                    className="px-2.5 py-1.5 bg-white hover:bg-neutral-100 text-[#1E252B] text-xs font-mono font-bold uppercase tracking-wider border border-[#E5E1D8] flex items-center gap-1.5 transition cursor-pointer"
                    title="Copy draft to clipboard"
                  >
                    {copied ? <Check className="h-3.5 w-3.5 text-emerald-600" /> : <Copy className="h-3.5 w-3.5" />}
                    {copied ? "Copied" : "Copy"}
                  </button>

                  <button
                    onClick={handleDownloadTxt}
                    className="px-2.5 py-1.5 bg-white hover:bg-neutral-100 text-[#1E252B] text-xs font-mono font-bold uppercase tracking-wider border border-[#E5E1D8] flex items-center gap-1 transition cursor-pointer"
                    title="Download as Markdown/Text"
                  >
                    .md
                  </button>

                  <button
                    onClick={handleResetToOriginal}
                    className="px-2.5 py-1.5 bg-white hover:bg-red-50 text-neutral-600 hover:text-red-700 text-xs font-mono border border-[#E5E1D8] flex items-center gap-1 transition cursor-pointer"
                    title="Reset edits to initial engine synthesis"
                  >
                    <RotateCcw className="h-3.5 w-3.5" />
                  </button>
                </div>
              </div>

              {/* Quick Legal Clause Insert Bar */}
              <div className="p-3 bg-[#FDFBF7] border border-[#E5E1D8] rounded-xs space-y-2">
                <div className="flex items-center gap-1.5 text-[10px] font-mono font-bold text-[#C5A059] uppercase tracking-wider">
                  <Sparkles className="h-3 w-3" />
                  Quick-Insert Statutory Pleading Clauses:
                </div>
                <div className="flex flex-wrap gap-2">
                  {quickClauses.map((clause, i) => (
                    <button
                      key={i}
                      onClick={() => insertClause(clause.text)}
                      className="px-2.5 py-1 bg-white hover:bg-[#1E252B] hover:text-[#FDFBF7] text-[#1E252B] border border-[#E5E1D8] hover:border-[#1E252B] text-[11px] font-sans flex items-center gap-1.5 rounded-xs transition cursor-pointer shadow-2xs"
                    >
                      <PlusCircle className="h-3 w-3 text-[#C5A059]" />
                      {clause.title}
                    </button>
                  ))}
                </div>
              </div>

              {/* Editor / Preview Body */}
              {activeTab === "preview" ? (
                <div className="bg-[#FAFBF9] border-l-4 border-l-[#C5A059] border-y border-r border-[#E5E1D8] p-5 sm:p-6 space-y-4 font-serif">
                  <div className="flex items-center justify-between border-b border-[#FAF9F5] pb-2.5 mb-1">
                    <span className="text-[10px] font-mono font-bold text-[#1E252B] uppercase tracking-widest flex items-center gap-1.5">
                      <CheckCircle className="h-3.5 w-3.5 text-emerald-600" />
                      Statutory Synthesis & Legal Draft Formatted
                    </span>
                    <span className="text-[10px] font-mono text-neutral-400">
                      Switch to "Edit Document" to modify text
                    </span>
                  </div>

                  <div className="space-y-3 font-serif text-xs text-[#1E252B] leading-relaxed max-h-[60vh] overflow-y-auto pr-2">
                    {renderMarkdown(memoResponse)}
                  </div>
                </div>
              ) : (
                <div className="space-y-2">
                  <div className="flex justify-between items-center text-[10px] font-mono text-neutral-500">
                    <span>Drafting Markdown Editor (Supports # Headers, - Lists, **Bold**)</span>
                    <span>Edits are saved in real time and reflected in DOCX & PDF exports</span>
                  </div>
                  <textarea
                    value={memoResponse}
                    onChange={(e) => setMemoResponse(e.target.value)}
                    rows={18}
                    className="w-full p-4 font-mono text-xs text-[#1E252B] bg-white border-2 border-[#1E252B] focus:border-[#C5A059] focus:outline-hidden leading-relaxed resize-y shadow-inner"
                    placeholder="Type or edit legal memorandum here..."
                  />
                </div>
              )}

              <div className="bg-[#FAF9F5] p-3 border border-[#E5E1D8] text-[10px] font-mono text-[#4A5560] leading-relaxed">
                <span className="font-bold text-[#1E252B] uppercase tracking-wider block mb-1">
                  💡 DRAFTING & EXPORT GUIDELINES:
                </span>
                Exporting to <strong>DOCX (.docx)</strong> produces an editable Microsoft Word / Google Docs file with formatted tables, headings, and pagination. <strong>Export PDF</strong> produces a secured document. You can freely edit and customize clauses above before exporting.
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
